from enum import Enum

class ErrorCodes(Enum):
    # Detection failures
    ORANGE_BAR_DETECTION_FAILURE = 101
    BLUE_BAR_DETECTION_FAILURE = 102
    PALLET_DETECTION_FAILURE = 103

    # OCR failures
    RACK_ID_NOT_FOUND = 201
    RACK_ID_NOT_ADJACENT = 202
    UNIQUE_ID_NOT_FOUND = 203

    # Data related errors
    BOXES_PER_LAYER_NOT_FOUND = 301
    ODD_LAYERING_NOT_FOUND = 302
    EVEN_LAYERING_NOT_FOUND = 303
    LAYERS_NOT_FOUND = 304
    STACKING_TYPE_NOT_FOUND = 305
    LAYER_WISE_DEPTH_DIFF_NOT_FOUND = 306
    RATIO_NOT_FOUND = 307
    FRONT_BOXES_NOT_FOUND = 308
    