[loggers]
keys=root
 
[handlers]
keys=rotatingFileHandler
 
[formatters]
keys=prodFormatter
 
[logger_root]
level=INFO
handlers=rotatingFileHandler

[handler_rotatingFileHandler]
class=logging.handlers.RotatingFileHandler
level=INFO
formatter=prodFormatter
args=('output/logs/main.log', 'a', 104857600, 5)
 
[formatter_prodFormatter]
format=%(asctime)s | %(levelname)s | %(name)s | %(filename)s:%(lineno)d | %(message)s
datefmt=%Y-%m-%d %H:%M:%S